### ISSUE TITLE
Reference to the paper

### ISSUE THREAD

**Issue by llrs** [hillarykoch/powerTCR#1]
Hi, I have seen you submitted the package to Bioconductor, thanks for doing so. 

In the README and in the vignette there are several references to your paper. Could you provide a link or a reference to read more about the models used and the main outcomes of your analysis?

Many thanks

**Comment by hillarykoch** [comment]
Hi there,

Unfortunately, the paper is not published yet. We are currently in the final stages of preparing the writing to submit to a journal, but were hoping to have an available package to point to when we submit the manuscript. All of those spots that say "**my paper**" are simply placeholders for where I need to enter the reference, when finally available.

In both the package and the manuscript, we do make a comparison to the model found here:
http://www.pnas.org/content/113/2/274
And provide code in powerTCR to fit this model and do clustering.

The style of model I am using is of that described in https://www.ine.pt/revstat/pdf/rs120102.pdf (jump to section 6 and 6.1) although the one implemented in powerTCR is for a discrete distribution. The ones described in the linked review are all continuous. The model is written out in mathematical terms in the package vignette as well

We also make classification comparisons to popular diversity estimators clonality (1-Pielou's evenness), shannon entropy, and species richness, all of which are implemented in the vegan package on CRAN.

Please let me know if there is anything else I can to to help resolve the current unavailability of my manuscript.

Thanks-

**Comment by llrs** [comment]
Is there a preprint of your manuscript I can read meanwhile? 
Many thanks, for the references too.

**Comment by hillarykoch** [comment]
Unfortunately no.  One of the data sets we used is currently unpublished and the data generators are not yet ready to publish it, so I am not sure that we will have a preprint.
