### ISSUE TITLE
tcR package will soon be orphaned

### ISSUE THREAD

**Issue by vadimnazarov** [hillarykoch/powerTCR#2]
Hi @hillarykoch ,

thank you for supporting the RepSeq community with your package! I would like to notify you that the tcR package will soon be orphaned in favour of our new package immunarch - https://github.com/immunomind/immunarch

I would be glad to help you move to the immunarch dependency. 

What parts of tcR do you use?

**Comment by hillarykoch** [comment]
Hi @vadimnazarov ,

Thanks for letting me know about this. My usage of tcR is fairly minimal, and contained entirely in the powerTCR/R/file_readers.R file. I use parse.file(), parse.folder(), and get.inframes()

I would appreciate any help! And will check out immunarch.

**Comment by vadimnazarov** [comment]
@hillarykoch , thank you for the prompt response!

Functions `parse.file()` and `parse.folder()` are combined into the singular function `repLoad` that automatically detects the input file format and always returns a list with two sub-lists `data` and `meta`. `data` is a list of repertoires. The data format for `immunarch` is a little bit different, feel free to take a look here: https://immunarch.com/articles/v2_data.html

`get.inframes` is now just `coding`.

I hope this will help you to get started, and please don't hesitate to ping me here. I will monitor this issue until it's closed.

Again, thank you a lot for your contribution!

**Comment by hillarykoch** [comment]
Right, hopefully just one quick question from me-- I am wondering what the structure is of the object returned from `repLoad`? I am only trying to extract the counts from the output of this file reader. So, currently, I have something like

```{r}
data <- tcR::parse.file(.filename = file, .format = format)
counts <- data$Read.count
```

I don't have any of the rep-seq data sitting around to play with to test this. Would the above code (assuming I change it `to immunarch::repLoad`) be correct in this case?

Thanks so much.

**Comment by vadimnazarov** [comment]
No, but it's easy to overcome. The `immunarch` code for this exact logic would be:

```
data <- immunarch::repLoad(.path = file)$data[[1]]
counts <- data$Clones
```

Note that there is no need to provide the `.format` argument.

**Comment by vadimnazarov** [comment]
Hi @hillarykoch , the `immunarch` is on CRAN now so feel free to test if powerTCR works!
